query Blogs {
  blogs {
      id
      title
      subtitle
      authors {
        firstName
        lastName
        relationship
      }
      date
      body
      attachments {
          url
      }
    }
}
